config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index' 
  
  get 'about', to: 'static_pages#about'
  
  resources :books, only: [:index, :show]
  resources :authors, only: [:index, :show]
  resources :publishers, only: [:index, :show]
  resources :categories, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  belongs_to :publisher
  belongs_to :category

  validates :title, presence: true
  validates :isbn, uniqueness: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books

  validates :name, presence: true, uniqueness: true
end

app/models/publisher.rb
class Publisher < ApplicationRecord
    has_many :books

    validates :name, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end

  def show
    @author = Author.find(params[:id])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    if params[:search]
      @books = Book.where("title LIKE ?", "%#{params[:search]}%")
    else
      @books = Book.all
    end

    @books = @books.order(:title).page(params[:page]).per(30)
  end

  def show
    @book = Book.find(params[:id])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  def index
    @publishers = Publisher.all
  end

  def show
    @publisher = Publisher.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/authors/index.html.erb
<h1>Authors</h1>
<ul>
  <% @authors.each do |author| %>
    <li><%= link_to author.name, author_path(author) %></li>
  <% end %>
</ul>

app/views/authors/show.html.erb
<h1><%= @author.name %></h1>
<ul>
  <% @author.books.each do |book| %>
    <li><%= link_to book.title, book_path(book) %></li>
  <% end %>
</ul>

app/views/books/index.html.erb
<h1>Lord of the Ruby</h1>

<%= form_with url: books_path, method: :get, local: true do %>
  <%= label_tag :search, "Search for a book:" %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search" %>
<% end %>

<% if @books.empty? %>
  <p>No books available.</p>
<% else %>
  <ul>
    <% @books.each do |book| %>
      <li><%= link_to book.title, book_path(book) %></li>
    <% end %>
  </ul>

  <%= paginate @books %>
<% end %>

app/views/books/show.html.erb
<h1><%= @book.title %></h1>
<p>Author: <%= link_to @book.author.name, author_path(@book.author) %></p>
<p>Publisher: <%= link_to @book.publisher.name, publisher_path(@book.publisher) %></p>
<p>Category: <%= link_to @book.category.name, category_path(@book.category) %></p>
<p>Publish Date: <%= @book.publish_date %></p>
<p>ISBN: <%= @book.isbn %></p>

app/views/categories/index.html.erb
<h1>Categories</h1>
<ul>
  <% @categories.each do |category| %>
    <li><%= link_to category.name, category_path(category) %></li>
  <% end %>
</ul>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<ul>
  <% @category.books.each do |book| %>
    <li><%= link_to book.title, book_path(book) %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lord of the Ruby</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
</head>

<body>
  <header>
    <nav>
      <%= link_to 'Home', root_path %> |
      <%= link_to 'Books', books_path %> |
      <%= link_to 'Authors', authors_path %> |
      <%= link_to 'Publishers', publishers_path %> |
      <%= link_to 'Categories', categories_path %> |
      <%= link_to 'About', about_path %>
    </nav>
  </header>

  <main>
    <%= yield %>
  </main>

  <footer>
    <p>&copy; 2024 Lord of the Ruby</p>
  </footer>
</body>
</html>

app/views/publishers/index.html.erb
<h1>Publishers</h1>
<ul>
  <% @publishers.each do |publisher| %>
    <li><%= link_to publisher.name, publisher_path(publisher) %></li>
  <% end %>
</ul>

app/views/publishers/show.html.erb
<h1><%= @publisher.name %></h1>
<ul>
  <% @publisher.books.each do |book| %>
    <li><%= link_to book.title, book_path(book) %></li>
  <% end %>
</ul>

app/views/static_pages/about.html.erb
<h1>About Lord of the Ruby</h1>
<p>Welcome to my book library. I got this data from the open library search api. The endpoint for this API is:
https://openlibrary.org/search.json.</p>

<p>Through this api, I took data from the books, authors, publishers and categories.</p>

<p>I pulled this data from four different sources adding this api.</p>

<p>This dataset was integrated by applying columns of book title, publish_date, publisher, category, author, etc.</p>